apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: the branch for the git repo
    - name: aws-access-key-id
      description: access key id
    - name: aws-secret-access-key
      description: secret access key
    - name: aws-default-region
      description: default region
    - name: endpoint-url
      description: endpoint url
    - name: s3-bucket
      description: s3 bucket
    - name: SCRIPT
      description: script
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: tec-pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: aws-access-key-id
          value: $(params.aws-access-key-id)
        - name: aws-secret-access-key
          value: $(params.aws-secret-access-key)
        - name: aws-default-region
          value: $(params.aws-default-region)
        - name: endpoint-url
          value: $(params.endpoint-url)
        - name: s3-bucket
          value: $(params.s3-bucket)
        - name: SCRIPT
          value: |
            aws --version
            aws s3 --endpoint-url $(params.endpoint-url) rm s3://$(params.s3-bucket) --recursive
            aws s3 --endpoint-url $(params.endpoint-url) cp /workspace/build s3://$(params.s3-bucket) --recursive
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "REPO_URL"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template